---
- name: "Deploy entitlement"
  when: entitlement_pem | default('', true) | trim != ''
  block:
  - name: "Ensure that the entitlement file 'entitlement_pem={{ entitlement_pem }}' exists"
    stat:
      path: '{{ entitlement_pem }}'
    register: entitlement_pem_stat
    failed_when: not entitlement_pem_stat.stat.exists

  - name: "Ensure that the entitlement RHSM file 'entitlement_rhsm={{ entitlement_rhsm }}' exists"
    stat:
      path: '{{ entitlement_rhsm }}'
    register: entitlement_rhsm_stat
    failed_when: not entitlement_rhsm_stat.stat.exists

  - name: Compute the md5sum of the entitlement files (debug)
    command: md5sum '{{ entitlement_rhsm }}' '{{ entitlement_pem }}'

  - name: "Deploy RHSM from file '{{ entitlement_rhsm }}'"
    shell:
      set -o pipefail;
      python3 "{{ entitlement_py_apply }}"
              "{{ entitlement_mc_rhsm }}" BASE64_ENCODED_RHSM_FILE "{{ entitlement_rhsm }}"
      | oc apply -f-

  - name: "Deploy the pem and key-pem from file '{{ entitlement_pem }}'"
    shell:
      set -o pipefail;
      python3 "{{ entitlement_py_apply }}"
              "{{ entitlement_mc_pem }}" BASE64_ENCODED_PEM_FILE "{{ entitlement_pem }}"
      | oc apply -f-

- name: "Deploy the yum client auth PEM from file '{{ entitlement_repo_yum_client_auth_pem_file }}' if requested"
  block:
  - name: Compute the md5sum of the client auth PEM file (debug)
    command: md5sum '{{ entitlement_repo_yum_client_auth_pem_file }}'

  - name: "Deploy the yum client auth PEM from file '{{ entitlement_mc_yum_client_auth }}'"
    shell:
      set -o pipefail;
      python3 "{{ entitlement_py_apply }}"
              "{{ entitlement_mc_yum_client_auth }}" BASE64_ENCODED_YUM_CLIENT_AUTH "{{ entitlement_repo_yum_client_auth_pem_file }}"
      | oc apply -f-
  when: entitlement_repo_yum_client_auth_pem_file | default('', true) | trim != ''
