name: Check the consistency of the repository

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install fire pyyaml

      - name: Check that all the variables point to existing files
        run: ./run.py repo validate_role_files

      - name: Check that all the variables defined are actually used
        run: ./run.py repo validate_role_vars_used
